const path = require('path');

const logs = (file) => path.join(process.env.HOME || '~', 'appstack', 'logs', file);

module.exports = {
  apps: [
    {
      name: 'orchestrator',
      cwd: 'apps/orchestrator',
      script: 'dist/index.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      watch: false,
      env: {
        NODE_ENV: 'production',
        PORT: '4000',
        OPENAI_API_KEY: process.env.OPENAI_API_KEY,
        VISION_API_KEY: process.env.VISION_API_KEY,
        CMS_URL: process.env.CMS_URL,
        STRAPI_URL: process.env.CMS_URL,
        STRAPI_TOKEN: process.env.STRAPI_TOKEN || '',
        REDIS_HOST: process.env.REDIS_HOST,
        REDIS_PORT: process.env.REDIS_PORT,
        REDIS_PASSWORD: process.env.REDIS_PASSWORD || '',
        CORS_ORIGINS: `${process.env.APP_URL},${process.env.API_URL}`,
        SENTRY_DSN: process.env.SENTRY_DSN || '',
        BETTERSTACK_HTTP_CHECK_URL: process.env.BETTERSTACK_HTTP_CHECK_URL || '',
        LOG_LEVEL: 'info',
      },
      error_file: logs('orchestrator.err.log'),
      out_file: logs('orchestrator.out.log'),
    },
    {
      name: 'cms',
      cwd: 'apps/cms',
      script: 'node_modules/.bin/strapi',
      args: 'start',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      watch: false,
      env: {
        NODE_ENV: 'production',
        HOST: '0.0.0.0',
        PORT: '1337',
        APP_KEYS: 'k1,k2,k3,k4',
        API_TOKEN_SALT: 'api_token_salt_here',
        ADMIN_JWT_SECRET: 'admin_jwt_secret_here',
        TRANSFER_TOKEN_SALT: 'transfer_token_salt_here',
        DATABASE_CLIENT: 'postgres',
        DATABASE_URL: process.env.POSTGRES_URL,
        URL: process.env.CMS_URL,
        S3_ENDPOINT: process.env.R2_ENDPOINT || '',
        S3_BUCKET: process.env.R2_BUCKET || '',
        S3_ACCESS_KEY_ID: process.env.R2_ACCESS_KEY_ID || '',
        S3_ACCESS_SECRET: process.env.R2_SECRET_ACCESS_KEY || '',
      },
      error_file: logs('cms.err.log'),
      out_file: logs('cms.out.log'),
    },
    {
      name: 'web',
      cwd: 'apps/web',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3000',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      watch: false,
      env: {
        NODE_ENV: 'production',
        NEXT_TELEMETRY_DISABLED: '1',
        NEXT_PUBLIC_API_BASE: process.env.API_URL,
        NEXT_PUBLIC_WS_BASE: process.env.API_URL,
      },
      error_file: logs('web.err.log'),
      out_file: logs('web.out.log'),
    },
  ],
};
